name: CI

on:
  push:
    branches:
      - production

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm config set @bit:registry https://node.bit.dev
        npm install npm-force-resolutions --save-dev
        rm -rf node_modules && npm install
        npx npm-force-resolutions
        npm install
        npm run-script build
      env:
        REACT_APP_APILINK: ${{ secrets.REACT_APP_APILINK }}
        REACT_APP_AESKEY: ${{ secrets.REACT_APP_AESKEY }}
        REACT_APP_AESIV: ${{ secrets.REACT_APP_AESIV }}
        REACT_APP_GOOGLE_ID: ${{ secrets.REACT_APP_GOOGLE_ID }}
        REACT_APP_TOKEN_SIGNATURE: ${{ secrets.REACT_APP_TOKEN_SIGNATURE }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build